---
title: "hw3"
format: html
---

https://github.com/nathanseaway/Homework_3.git

```{r}
library(tidyverse)
library(here)
library(gt)
library(flextable)
library(janitor)
library(readxl)

```

a.
To summarize my data I can take the mean of the number of times I apply sunscreen (response variable) compared between the two categorical groups: went to beach and did not go to beach (predictor variable). This allows me to compare the relation between going to the beach in a day and applying sunscreen, as I believe I apply sunscreen more on days when I go to the beach. 

b.
```{r}
library(dplyr)

sunscreen <- read.csv("sunscreen_fixed.csv")

sunscreen <- select(sunscreen, -Date, -Steps._Day, -Days._Spring, -Max._UV, -Max._Temp)

sunscreen <- sunscreen %>%

mutate(Beach = recode(Beach, "Y" = "Yes", "N" = "No"))

library(ggplot2)

# Create summary with lowercase names

sunscreen_summary <- sunscreen %>%

group_by(Beach) %>%

summarise(

mean = mean(Frequency_Sunscreen_Application),

sd = sd(Frequency_Sunscreen_Application)

)

# Plot

ggplot(sunscreen, aes(x = Beach, y = Frequency_Sunscreen_Application, color = Beach)) +
  geom_jitter(width = 0.1, height = 0, size = 2, alpha = 0.7) +
  scale_color_manual(values = c("No"= "lightgreen", "Yes"= "tan")) +
  geom_point(data = sunscreen_summary, aes(x = Beach, y = mean),
             color = "lightgoldenrod", size = 4, inherit.aes = FALSE) +
  geom_errorbar(data = sunscreen_summary,
                aes(x = Beach, ymin = mean - sd, ymax = mean + sd),
                width = 0.2, color = "#687", inherit.aes = FALSE) +
  labs(
    title = "Frequency Sunscreen Application by Beach Attendance",
    x = "Went to Beach: Yes or No",
    y = "Frequency of Sunscreen Application"
  ) +
  theme_minimal()

```

